### ISSUE TITLE
Table of Contents- Perhaps in ReadMe

### ISSUE THREAD

**Issue by DaneeTheDeveloper** [Minimal-APIs/minimal-apis.github.io#66]
What would you like see:
[ ] Documentation
[ ] Sample
[ ] Tutorial

What kind of content are you looking for ?

**Comment by DaneeTheDeveloper** [comment]
Table of contents. Perhaps in the ReadMe doc? I would like to see a guide on how to read these documents from  beginning to the end so that I am not jumping around from file to file. Is that possible?

**Comment by LadyNaggaga** [comment]
The table of content is on the sidebar.
![image](https://user-images.githubusercontent.com/2546640/135728962-a4e65244-7b6d-4276-94a6-d06d4aede287.png)

At the bottom of each page, you should see a next section 

![image](https://user-images.githubusercontent.com/2546640/135729024-0ce84b5b-d039-43a6-9038-767b91cc13c0.png)

Let me know if you have some  ideas on how we could improve this :) 

Thanks for the feedback

**Comment by DaneeTheDeveloper** [comment]
Got it! Sorry, I was looking in the GitHub pages. Didn't realize the website was up!
