### ISSUE TITLE
HTTP Methods Overview in Quick Start

### ISSUE THREAD

**Issue by DaneeTheDeveloper** [Minimal-APIs/minimal-apis.github.io#67]
I tried out the following code provided in the doc 

```
app.MapGet("/hello", () => "Hello World!");
app.MapGet("/todos", () => new { TodoItem = "Learn about routing", Complete = false });
app.MapPost("/todos", () => Result.Ok());
```

And I received the following error message-

> (6,29): error CS0103: The name 'Result' does not exist in the current context

Just want to make note of that!

**Comment by LadyNaggaga** [comment]
Thank  you @DaneeTheDeveloper   can you please confirm what version of .NET you have installed ?

**Comment by DaneeTheDeveloper** [comment]
![Screen Shot 2021-10-02 at 10 07 28 AM](https://user-images.githubusercontent.com/71569075/135725983-22311a9f-dbb8-470c-a248-596221c6c0b6.png)

Hi @LadyNaggaga 

I am currently using .NET 6. I'm going to delete my bin and obj files and do 'dotnet restore' to see if it will continue to happen.

**Comment by DaneeTheDeveloper** [comment]
I deleted the files and did 'dotnet restore', ran it again and it failed.
![Screen Shot 2021-10-02 at 10 10 54 AM](https://user-images.githubusercontent.com/71569075/135726069-edad8300-e2e9-4b07-b5ed-418d458aa4e4.png)
![Screen Shot 2021-10-02 at 10 11 57 AM](https://user-images.githubusercontent.com/71569075/135726090-60f94c50-4f22-4c4d-b69d-6a3db29b6a0c.png)

**Comment by davidfowl** [comment]
What version of .NET 6? Make sure you have the [latest preview](https://dotnet.microsoft.com/download/dotnet/6.0).

**Comment by DaneeTheDeveloper** [comment]
I ran 'dotnet --list-sdks' in the terminal and it returned the following

![Screen Shot 2021-10-02 at 10 35 50 AM](https://user-images.githubusercontent.com/71569075/135726723-94e2c876-4a54-4487-8752-f8760200b036.png)

**Comment by DaneeTheDeveloper** [comment]
The editor I'm using is VS code.

**Comment by davidfowl** [comment]
That looks good. What happens if you run `dotnet build` from the command line? If that works, you might need to update your VS code csharp extension.

**Comment by DaneeTheDeveloper** [comment]
I ran `dotnet build` in the terminal and it returned the following

![Screen Shot 2021-10-02 at 10 40 58 AM](https://user-images.githubusercontent.com/71569075/135726876-1bd845ef-687f-4ee0-b657-f965ed9fd2da.png)

**Comment by davidfowl** [comment]
Ah, it's Results with an s 😄 `Results.Ok`

**Comment by davidfowl** [comment]
Fixed the doc

**Comment by DaneeTheDeveloper** [comment]
Tested 'Results' out on my end and it worked! 😄 Thanks for the update!
