### ISSUE TITLE
404 for logo.png

### ISSUE THREAD

**Issue by davidfowl** [Minimal-APIs/minimal-apis.github.io#69]
![image](https://user-images.githubusercontent.com/95136/135730323-d42c9353-5b4c-4769-b596-f92c6f3a100e.png)

**Comment by LadyNaggaga** [comment]
![image](https://user-images.githubusercontent.com/2546640/135853979-2e54c9a6-e187-41dc-bce8-3fe16a1fde09.png)
I am unable to repro this.

**Comment by LadyNaggaga** [comment]
I haven't been able to repro this bug.
